// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5sbOKVOluOBwiLgmgVGV02gTDvmt-zcw',
    appId: '1:859204587040:web:028e124070d489e2203645',
    messagingSenderId: '859204587040',
    projectId: 'smartclassroommontoring',
    authDomain: 'smartclassroommontoring.firebaseapp.com',
    storageBucket: 'smartclassroommontoring.firebasestorage.app',
    measurementId: 'G-CVPTR27EZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gfY45rErVh5wZij2CCMnrYXs1TqXkzA',
    appId: '1:859204587040:android:482712043611d5b5203645',
    messagingSenderId: '859204587040',
    projectId: 'smartclassroommontoring',
    storageBucket: 'smartclassroommontoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Q36lL7uy_GnScH6kNfFx1gU6aa6RfOg',
    appId: '1:859204587040:ios:4e69015b4054b292203645',
    messagingSenderId: '859204587040',
    projectId: 'smartclassroommontoring',
    storageBucket: 'smartclassroommontoring.firebasestorage.app',
    iosBundleId: 'com.smartclassroom.smartClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Q36lL7uy_GnScH6kNfFx1gU6aa6RfOg',
    appId: '1:859204587040:ios:4e69015b4054b292203645',
    messagingSenderId: '859204587040',
    projectId: 'smartclassroommontoring',
    storageBucket: 'smartclassroommontoring.firebasestorage.app',
    iosBundleId: 'com.smartclassroom.smartClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5sbOKVOluOBwiLgmgVGV02gTDvmt-zcw',
    appId: '1:859204587040:web:e25e74d290516153203645',
    messagingSenderId: '859204587040',
    projectId: 'smartclassroommontoring',
    authDomain: 'smartclassroommontoring.firebaseapp.com',
    storageBucket: 'smartclassroommontoring.firebasestorage.app',
    measurementId: 'G-XLHB20B7QG',
  );
}
